name: plotlyTest
channels:
  - conda-forge
  - defaults
  - plotly
  - fastai
dependencies:
  - jupyterlab
  - panel>=0.12.7
  - ipywidgets
  - numpy
  - nbdev=2.3.12
  - fastcore=1.5.28
  - plotly=5.15.0
